services:
  express:
    build:
      context: ./
      dockerfile: DockerfileDev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node-express
    command: ["nodemon", "-L", "index.js"]

networks:
  node-express:
    
